### ISSUE TITLE
Name does not resolve, API crash

### ISSUE THREAD

**Issue by spijker** [daspanel/daspanel#1]
Just did git clone 
docker-compose up
Login works -> on the site-module , then the api crashes

daspanel-panel_1              | 172.19.0.8 - - [03/Mar/2017 12:39:03] "GET / HTTP/1.1" 200 -
daspanel-panel_1              | [2017-03-03 12:39:05,622] ERROR in app: Exception on /sites/ [GET]
daspanel-panel_1              | Traceback (most recent call last):
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
daspanel-panel_1              |     response = self.full_dispatch_request()
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
daspanel-panel_1              |     rv = self.handle_user_exception(e)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
daspanel-panel_1              |     reraise(exc_type, exc_value, tb)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
daspanel-panel_1              |     rv = self.dispatch_request()
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
daspanel-panel_1              |     return self.view_functions[rule.endpoint](**req.view_args)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
daspanel-panel_1              |     return func(*args, **kwargs)
daspanel-panel_1              |   File "/opt/daspanel/apps/panel/daspanel_web/modules/sites/views.py", line 167, in home
daspanel-panel_1              |     result = api.get_all()
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/devourer/api.py", line 269, in <lambda>
daspanel-panel_1              |     return lambda obj, *args, **kwargs: obj.call(name, *args, **kwargs)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/devourer/api.py", line 256, in call
daspanel-panel_1              |     prepared.call(self, *prepared.args, **prepared.kwargs),
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/devourer/api.py", line 134, in __call__
daspanel-panel_1              |     requests_kwargs=self.requests_kwargs)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/devourer/api.py", line 286, in invoke
daspanel-panel_1              |     headers=headers, **kwargs)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
daspanel-panel_1              |     return request('get', url, params=params, **kwargs)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
daspanel-panel_1              |     return session.request(method=method, url=url, **kwargs)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
daspanel-panel_1              |     resp = self.send(prep, **send_kwargs)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
daspanel-panel_1              |     r = adapter.send(request, **kwargs)
daspanel-panel_1              |   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
daspanel-panel_1              |     raise ConnectionError(e, request=request)
daspanel-panel_1              | ConnectionError: HTTPConnectionPool(host='daspanel-api', port=8080): Max retries exceeded with url: /1.0/sites/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7dab5b17d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
daspanel-panel_1              | 172.19.0.8 - - [03/Mar/2017 12:39:05] "GET /sites/ HTTP/1.1" 500 -

**Comment by abnerjacobsen** [comment]
Thanks for reporting this bug.

This occurred because you did not configure an valid SMTP service in the smtp.env file.

The container daspanel-api sends at the end of its initialization an email with the basic credentials of access to the control panel.

I changed the container initialization script and now even when an email sending error occurs its initialization is completed successfully.

Please update the container by running the following commands:

docker-compose down
docker rmi daspanel/api-server:latest-dev
docker-compose up -d 

Let's me know if this bugfix solved the problem.
